// Tailwind v3 config for the WebUI shell (ADR 0009, ADR 0010).
//
// Token names map 1:1 onto the desktop application's design tokens
// (see docs/webui-visual-language.md and packages/webui/src/client/styles/tokens.css).
// Every utility whose name starts with a token family — bg_*, text_*, border_*,
// shadow_*, radius_*, spacing_*, size_*, line_height_* — is generated from the
// corresponding CSS variable so the WebUI and the desktop application share
// one naming surface.

const tailwindConfig = {
  content: [
    "./src/client/**/*.{ts,tsx,html}",
  ],
  theme: {
    backgroundColor: {
      transparent: "transparent",
      current: "currentColor",
      inherit: "inherit",
      "bg_default_primary": "var(--bg_default_primary)",
      "bg_default_primary_elevated": "var(--bg_default_primary_elevated)",
      "bg_default_scrim": "var(--bg_default_scrim)",
      "bg_default_secondary": "var(--bg_default_secondary)",
      "bg_default_secondary_elevated": "var(--bg_default_secondary_elevated)",
      "bg_default_tertiary": "var(--bg_default_tertiary)",
      "bg_default_tertiary_elevated": "var(--bg_default_tertiary_elevated)",
      "bg_grouped_primary": "var(--bg_grouped_primary)",
      "bg_grouped_primary_elevated": "var(--bg_grouped_primary_elevated)",
      "bg_grouped_secondary": "var(--bg_grouped_secondary)",
      "bg_grouped_secondary_elevated": "var(--bg_grouped_secondary_elevated)",
      "bg_grouped_tertiary": "var(--bg_grouped_tertiary)",
      "bg_grouped_tertiary_elevated": "var(--bg_grouped_tertiary_elevated)",
      "bg_interaction_accent_default": "var(--bg_interaction_accent_default)",
      "bg_interaction_accent_focus_blue": "var(--bg_interaction_accent_focus_blue)",
      "bg_interaction_accent_focus_highlight": "var(--bg_interaction_accent_focus_highlight)",
      "bg_interaction_accent_hover": "var(--bg_interaction_accent_hover)",
      "bg_interaction_accent_inactive": "var(--bg_interaction_accent_inactive)",
      "bg_interaction_accent_press": "var(--bg_interaction_accent_press)",
      "bg_interaction_danger_primary_default": "var(--bg_interaction_danger_primary_default)",
      "bg_interaction_danger_primary_hover": "var(--bg_interaction_danger_primary_hover)",
      "bg_interaction_danger_primary_inactive": "var(--bg_interaction_danger_primary_inactive)",
      "bg_interaction_danger_primary_press": "var(--bg_interaction_danger_primary_press)",
      "bg_interaction_danger_secondary_default": "var(--bg_interaction_danger_secondary_default)",
      "bg_interaction_danger_secondary_hover": "var(--bg_interaction_danger_secondary_hover)",
      "bg_interaction_danger_secondary_inactive": "var(--bg_interaction_danger_secondary_inactive)",
      "bg_interaction_danger_secondary_press": "var(--bg_interaction_danger_secondary_press)",
      "bg_interaction_positive_default": "var(--bg_interaction_positive_default)",
      "bg_interaction_positive_hover": "var(--bg_interaction_positive_hover)",
      "bg_interaction_positive_inactive": "var(--bg_interaction_positive_inactive)",
      "bg_interaction_positive_press": "var(--bg_interaction_positive_press)",
      "bg_interaction_primary_default": "var(--bg_interaction_primary_default)",
      "bg_interaction_primary_hover": "var(--bg_interaction_primary_hover)",
      "bg_interaction_primary_inactive": "var(--bg_interaction_primary_inactive)",
      "bg_interaction_primary_press": "var(--bg_interaction_primary_press)",
      "bg_interaction_primary_selected": "var(--bg_interaction_primary_selected)",
      "bg_interaction_secondary_default": "var(--bg_interaction_secondary_default)",
      "bg_interaction_secondary_hover": "var(--bg_interaction_secondary_hover)",
      "bg_interaction_secondary_inactive": "var(--bg_interaction_secondary_inactive)",
      "bg_interaction_secondary_press": "var(--bg_interaction_secondary_press)",
      "bg_interaction_secondary_selected": "var(--bg_interaction_secondary_selected)",
      "bg_interaction_tertiary_default": "var(--bg_interaction_tertiary_default)",
      "bg_interaction_tertiary_hover": "var(--bg_interaction_tertiary_hover)",
      "bg_interaction_tertiary_inactive": "var(--bg_interaction_tertiary_inactive)",
      "bg_interaction_tertiary_press": "var(--bg_interaction_tertiary_press)",
      "bg_interaction_tertiary_selected": "var(--bg_interaction_tertiary_selected)",
      "bg_interaction_video_generation_default": "var(--bg_interaction_video_generation_default)",
      "bg_interaction_video_generation_hover": "var(--bg_interaction_video_generation_hover)",
      "bg_interaction_video_generation_selected": "var(--bg_interaction_video_generation_selected)",
      "bg_interaction_warning_default": "var(--bg_interaction_warning_default)",
      "bg_interaction_warning_hover": "var(--bg_interaction_warning_hover)",
      "bg_interaction_warning_inactive": "var(--bg_interaction_warning_inactive)",
      "bg_interaction_warning_press": "var(--bg_interaction_warning_press)",
      "bg_status_blue": "var(--bg_status_blue)",
      "bg_status_error": "var(--bg_status_error)",
      "bg_status_positive": "var(--bg_status_positive)",
      "bg_status_tag": "var(--bg_status_tag)",
      "bg_status_video_generation": "var(--bg_status_video_generation)",
      "bg_status_warning": "var(--bg_status_warning)",
      "utility_overlay": "var(--utility_overlay)",
      "utility_popover": "var(--utility_popover)",
      "utility_scrim": "var(--utility_scrim)",
      "utility_scrollbar": "var(--utility_scrollbar)",
      "utility_tootip": "var(--utility_tootip)",
    },
    textColor: {
      transparent: "transparent",
      current: "currentColor",
      inherit: "inherit",
      "text_default_accent": "var(--text_default_accent)",
      "text_default_inverted": "var(--text_default_inverted)",
      "text_default_inverted_static": "var(--text_default_inverted_static)",
      "text_default_primary": "var(--text_default_primary)",
      "text_default_quaternary": "var(--text_default_quaternary)",
      "text_default_secondary": "var(--text_default_secondary)",
      "text_default_tertiary": "var(--text_default_tertiary)",
      "text_label_accent_default": "var(--text_label_accent_default)",
      "text_label_accent_hover": "var(--text_label_accent_hover)",
      "text_label_accent_inactive": "var(--text_label_accent_inactive)",
      "text_label_accent_press": "var(--text_label_accent_press)",
      "text_label_danger_primary_default": "var(--text_label_danger_primary_default)",
      "text_label_danger_primary_hover": "var(--text_label_danger_primary_hover)",
      "text_label_danger_primary_inactive": "var(--text_label_danger_primary_inactive)",
      "text_label_danger_primary_press": "var(--text_label_danger_primary_press)",
      "text_label_danger_secondary_default": "var(--text_label_danger_secondary_default)",
      "text_label_danger_secondary_hover": "var(--text_label_danger_secondary_hover)",
      "text_label_danger_secondary_inactive": "var(--text_label_danger_secondary_inactive)",
      "text_label_danger_secondary_press": "var(--text_label_danger_secondary_press)",
      "text_label_positive_primary_default": "var(--text_label_positive_primary_default)",
      "text_label_positive_primary_hover": "var(--text_label_positive_primary_hover)",
      "text_label_positive_primary_inactive": "var(--text_label_positive_primary_inactive)",
      "text_label_positive_primary_press": "var(--text_label_positive_primary_press)",
      "text_label_positive_secondary_default": "var(--text_label_positive_secondary_default)",
      "text_label_positive_secondary_hover": "var(--text_label_positive_secondary_hover)",
      "text_label_positive_secondary_inactive": "var(--text_label_positive_secondary_inactive)",
      "text_label_positive_secondary_press": "var(--text_label_positive_secondary_press)",
      "text_label_primary_default": "var(--text_label_primary_default)",
      "text_label_primary_hover": "var(--text_label_primary_hover)",
      "text_label_primary_inactive": "var(--text_label_primary_inactive)",
      "text_label_primary_press": "var(--text_label_primary_press)",
      "text_label_primary_selected": "var(--text_label_primary_selected)",
      "text_label_secondary_default": "var(--text_label_secondary_default)",
      "text_label_secondary_hover": "var(--text_label_secondary_hover)",
      "text_label_secondary_inactive": "var(--text_label_secondary_inactive)",
      "text_label_secondary_press": "var(--text_label_secondary_press)",
      "text_label_secondary_selected": "var(--text_label_secondary_selected)",
      "text_label_tertiary_default": "var(--text_label_tertiary_default)",
      "text_label_tertiary_hover": "var(--text_label_tertiary_hover)",
      "text_label_tertiary_inactive": "var(--text_label_tertiary_inactive)",
      "text_label_tertiary_press": "var(--text_label_tertiary_press)",
      "text_label_tertiary_selected": "var(--text_label_tertiary_selected)",
      "text_label_warning_primary_default": "var(--text_label_warning_primary_default)",
      "text_label_warning_primary_hover": "var(--text_label_warning_primary_hover)",
      "text_label_warning_primary_inactive": "var(--text_label_warning_primary_inactive)",
      "text_label_warning_primary_press": "var(--text_label_warning_primary_press)",
      "text_label_warning_secondary_default": "var(--text_label_warning_secondary_default)",
      "text_label_warning_secondary_hover": "var(--text_label_warning_secondary_hover)",
      "text_label_warning_secondary_inactive": "var(--text_label_warning_secondary_inactive)",
      "text_label_warning_secondary_press": "var(--text_label_warning_secondary_press)",
      "text_status_banana": "var(--text_status_banana)",
      "text_status_blue": "var(--text_status_blue)",
      "text_status_error": "var(--text_status_error)",
      "text_status_success": "var(--text_status_success)",
      "text_status_video_generation": "var(--text_status_video_generation)",
      "text_status_warning": "var(--text_status_warning)",
      "icon_default_accent": "var(--icon_default_accent)",
      "icon_default_inverted": "var(--icon_default_inverted)",
      "icon_default_inverted_static": "var(--icon_default_inverted_static)",
      "icon_default_primary": "var(--icon_default_primary)",
      "icon_default_quaternary": "var(--icon_default_quaternary)",
      "icon_default_secondary": "var(--icon_default_secondary)",
      "icon_default_tertiary": "var(--icon_default_tertiary)",
      "icon_interaction_accent_accent": "var(--icon_interaction_accent_accent)",
      "icon_interaction_accent_default": "var(--icon_interaction_accent_default)",
      "icon_interaction_accent_hover": "var(--icon_interaction_accent_hover)",
      "icon_interaction_accent_inactive": "var(--icon_interaction_accent_inactive)",
      "icon_interaction_accent_press": "var(--icon_interaction_accent_press)",
      "icon_interaction_danger_primary_default": "var(--icon_interaction_danger_primary_default)",
      "icon_interaction_danger_primary_hover": "var(--icon_interaction_danger_primary_hover)",
      "icon_interaction_danger_primary_inactive": "var(--icon_interaction_danger_primary_inactive)",
      "icon_interaction_danger_primary_press": "var(--icon_interaction_danger_primary_press)",
      "icon_interaction_danger_secondary_default": "var(--icon_interaction_danger_secondary_default)",
      "icon_interaction_danger_secondary_hover": "var(--icon_interaction_danger_secondary_hover)",
      "icon_interaction_danger_secondary_inactive": "var(--icon_interaction_danger_secondary_inactive)",
      "icon_interaction_danger_secondary_press": "var(--icon_interaction_danger_secondary_press)",
      "icon_interaction_positive_primary_default": "var(--icon_interaction_positive_primary_default)",
      "icon_interaction_positive_primary_hover": "var(--icon_interaction_positive_primary_hover)",
      "icon_interaction_positive_primary_inactive": "var(--icon_interaction_positive_primary_inactive)",
      "icon_interaction_positive_primary_press": "var(--icon_interaction_positive_primary_press)",
      "icon_interaction_positive_secondary_default": "var(--icon_interaction_positive_secondary_default)",
      "icon_interaction_positive_secondary_hover": "var(--icon_interaction_positive_secondary_hover)",
      "icon_interaction_positive_secondary_inactive": "var(--icon_interaction_positive_secondary_inactive)",
      "icon_interaction_positive_secondary_press": "var(--icon_interaction_positive_secondary_press)",
      "icon_interaction_primary_default": "var(--icon_interaction_primary_default)",
      "icon_interaction_primary_hover": "var(--icon_interaction_primary_hover)",
      "icon_interaction_primary_inactive": "var(--icon_interaction_primary_inactive)",
      "icon_interaction_primary_press": "var(--icon_interaction_primary_press)",
      "icon_interaction_primary_selected": "var(--icon_interaction_primary_selected)",
      "icon_interaction_secondary_default": "var(--icon_interaction_secondary_default)",
      "icon_interaction_secondary_hover": "var(--icon_interaction_secondary_hover)",
      "icon_interaction_secondary_inactive": "var(--icon_interaction_secondary_inactive)",
      "icon_interaction_secondary_press": "var(--icon_interaction_secondary_press)",
      "icon_interaction_secondary_selected": "var(--icon_interaction_secondary_selected)",
      "icon_interaction_tertiary_default": "var(--icon_interaction_tertiary_default)",
      "icon_interaction_tertiary_hover": "var(--icon_interaction_tertiary_hover)",
      "icon_interaction_tertiary_inactive": "var(--icon_interaction_tertiary_inactive)",
      "icon_interaction_tertiary_press": "var(--icon_interaction_tertiary_press)",
      "icon_interaction_tertiary_selected": "var(--icon_interaction_tertiary_selected)",
      "icon_interaction_warning_primary_default": "var(--icon_interaction_warning_primary_default)",
      "icon_interaction_warning_primary_hover": "var(--icon_interaction_warning_primary_hover)",
      "icon_interaction_warning_primary_inactive": "var(--icon_interaction_warning_primary_inactive)",
      "icon_interaction_warning_primary_press": "var(--icon_interaction_warning_primary_press)",
      "icon_interaction_warning_secondary_default": "var(--icon_interaction_warning_secondary_default)",
      "icon_interaction_warning_secondary_hover": "var(--icon_interaction_warning_secondary_hover)",
      "icon_interaction_warning_secondary_inactive": "var(--icon_interaction_warning_secondary_inactive)",
      "icon_interaction_warning_secondary_press": "var(--icon_interaction_warning_secondary_press)",
      "icon_status_error": "var(--icon_status_error)",
      "icon_status_success": "var(--icon_status_success)",
      "icon_status_warning": "var(--icon_status_warning)",
      "terminal_ansi_black": "var(--terminal_ansi_black)",
      "terminal_ansi_blue": "var(--terminal_ansi_blue)",
      "terminal_ansi_bright_black": "var(--terminal_ansi_bright_black)",
      "terminal_ansi_bright_blue": "var(--terminal_ansi_bright_blue)",
      "terminal_ansi_bright_cyan": "var(--terminal_ansi_bright_cyan)",
      "terminal_ansi_bright_green": "var(--terminal_ansi_bright_green)",
      "terminal_ansi_bright_magenta": "var(--terminal_ansi_bright_magenta)",
      "terminal_ansi_bright_red": "var(--terminal_ansi_bright_red)",
      "terminal_ansi_bright_white": "var(--terminal_ansi_bright_white)",
      "terminal_ansi_bright_yellow": "var(--terminal_ansi_bright_yellow)",
      "terminal_ansi_cyan": "var(--terminal_ansi_cyan)",
      "terminal_ansi_green": "var(--terminal_ansi_green)",
      "terminal_ansi_magenta": "var(--terminal_ansi_magenta)",
      "terminal_ansi_red": "var(--terminal_ansi_red)",
      "terminal_ansi_white": "var(--terminal_ansi_white)",
      "terminal_ansi_yellow": "var(--terminal_ansi_yellow)",
      "terminal_cursor": "var(--terminal_cursor)",
      "terminal_cursor_accent": "var(--terminal_cursor_accent)",
      "terminal_foreground": "var(--terminal_foreground)",
      "terminal_selection": "var(--terminal_selection)",
    },
    borderColor: {
      transparent: "transparent",
      current: "currentColor",
      inherit: "inherit",
      "border_accent": "var(--border_accent)",
      "border_danger_default": "var(--border_danger_default)",
      "border_danger_hover": "var(--border_danger_hover)",
      "border_danger_inactive": "var(--border_danger_inactive)",
      "border_danger_press": "var(--border_danger_press)",
      "border_default": "var(--border_default)",
      "border_heavy": "var(--border_heavy)",
      "border_light": "var(--border_light)",
      "border_status_blue": "var(--border_status_blue)",
      "border_status_error": "var(--border_status_error)",
      "border_status_success": "var(--border_status_success)",
      "border_status_warning": "var(--border_status_warning)",
      "border_tertiary_default": "var(--border_tertiary_default)",
      "border_tertiary_hover": "var(--border_tertiary_hover)",
      "border_tertiary_inactive": "var(--border_tertiary_inactive)",
      "border_tertiary_press": "var(--border_tertiary_press)",
    },
    boxShadow: {
      none: "none",
      "shadow_default": "var(--shadow_default)",
    },
    borderRadius: {
      none: "0",
      full: "9999px",
      "radius_12": "var(--radius_12)",
      "radius_16": "var(--radius_16)",
      "radius_20": "var(--radius_20)",
      "radius_24": "var(--radius_24)",
      "radius_32": "var(--radius_32)",
      "radius_4": "var(--radius_4)",
      "radius_8": "var(--radius_8)",
      "radius_full": "var(--radius_full)",
    },
    spacing: {
      "spacing_0": "var(--spacing_0)",
      "spacing_12": "var(--spacing_12)",
      "spacing_128": "var(--spacing_128)",
      "spacing_16": "var(--spacing_16)",
      "spacing_2": "var(--spacing_2)",
      "spacing_20": "var(--spacing_20)",
      "spacing_24": "var(--spacing_24)",
      "spacing_32": "var(--spacing_32)",
      "spacing_4": "var(--spacing_4)",
      "spacing_40": "var(--spacing_40)",
      "spacing_48": "var(--spacing_48)",
      "spacing_6": "var(--spacing_6)",
      "spacing_64": "var(--spacing_64)",
      "spacing_8": "var(--spacing_8)",
      "spacing_90": "var(--spacing_90)",
      "size_12": "var(--size_12)",
      "size_14": "var(--size_14)",
      "size_16": "var(--size_16)",
      "size_20": "var(--size_20)",
      "size_24": "var(--size_24)",
      "size_32": "var(--size_32)",
      "size_40": "var(--size_40)",
      "size_48": "var(--size_48)",
      "size_64": "var(--size_64)",
    },
    size: {
      "size_12": "var(--size_12)",
      "size_14": "var(--size_14)",
      "size_16": "var(--size_16)",
      "size_20": "var(--size_20)",
      "size_24": "var(--size_24)",
      "size_32": "var(--size_32)",
      "size_40": "var(--size_40)",
      "size_48": "var(--size_48)",
      "size_64": "var(--size_64)",
    },
    lineHeight: {
      "line_height_16": "var(--line_height_16)",
      "line_height_18": "var(--line_height_18)",
      "line_height_20": "var(--line_height_20)",
      "line_height_22": "var(--line_height_22)",
      "line_height_26": "var(--line_height_26)",
      "line_height_28": "var(--line_height_28)",
      "line_height_36": "var(--line_height_36)",
      "line_height_40": "var(--line_height_40)",
    },
    fontWeight: {
      "weight_medium": "var(--weight_medium)",
      "weight_regular": "var(--weight_regular)",
    },
    fontFamily: {
      sans: [
        '"HarmonyOS Sans"',
        '"Segoe UI"',
        '"SF Pro Display"',
        "-apple-system",
        "BlinkMacSystemFont",
        "Roboto",
        "Oxygen",
        "Ubuntu",
        "Cantarell",
        '"Open Sans"',
        '"Helvetica Neue"',
        "sans-serif",
        // Chinese fallbacks — desktop's preflight stack.
        '"HarmonyOS Sans SC"',
        '"PingFang SC"',
        '"Hiragino Sans GB"',
        '"Microsoft Yahei UI"',
        '"Microsoft Yahei"',
        '"Source Han Sans CN"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Apple Color Emoji"',
        '"Twemoji Mozilla"',
        '"Noto Color Emoji"',
        '"Android Emoji"',
      ],
      serif: ['"SourceSerif"', '"Source Serif Pro"', "Georgia", "serif"],
      mono: [
        '"Hack"',
        "ui-monospace",
        "SFMono-Regular",
        '"SF Mono"',
        "Menlo",
        "Consolas",
        // Chinese fallbacks — desktop's preflight stack.
        '"HarmonyOS Sans SC"',
        '"PingFang SC"',
        "monospace",
      ],
    },
    extend: {
      colors: {
      "blue_400": "var(--blue_400)",
      "blue_500": "var(--blue_500)",
      "blue_600": "var(--blue_600)",
      "violet_500": "var(--violet_500)",
      },
      // The desktop's markup composes two scales at once: the token-named utilities
      // above (`p-spacing_16`, `rounded-radius_12`) and Tailwind's stock numeric scale
      // (`h-8`, `gap-2`, `p-3`, `rounded-lg`, `size-7`, `leading-4`). Replacing
      // `spacing` / `borderRadius` / `lineHeight` / `fontWeight` / `size` outright above
      // left the second set ungenerated, so a class composition lifted from the desktop
      // compiled to nothing here. These restore the stock values, which are the ones the
      // desktop's own stylesheet ships; the token-named keys stay the project's
      // vocabulary for anything the tokens describe.
      spacing: {
        px: "1px",
        "0": "0px",
        "0.5": "0.125rem",
        "1": "0.25rem",
        "1.5": "0.375rem",
        "2": "0.5rem",
        "2.5": "0.625rem",
        "3": "0.75rem",
        "3.5": "0.875rem",
        "4": "1rem",
        "5": "1.25rem",
        "6": "1.5rem",
        "7": "1.75rem",
        "8": "2rem",
        "9": "2.25rem",
        "10": "2.5rem",
        "11": "2.75rem",
        "12": "3rem",
        "14": "3.5rem",
        "16": "4rem",
        "20": "5rem",
        "24": "6rem",
        "28": "7rem",
        "32": "8rem",
        "36": "9rem",
        "40": "10rem",
        "44": "11rem",
        "48": "12rem",
        "52": "13rem",
        "56": "14rem",
        "60": "15rem",
        "64": "16rem",
        "72": "18rem",
        "80": "20rem",
        "96": "24rem",
      },
      size: {
        px: "1px",
        "0": "0px",
        "0.5": "0.125rem",
        "1": "0.25rem",
        "1.5": "0.375rem",
        "2": "0.5rem",
        "2.5": "0.625rem",
        "3": "0.75rem",
        "3.5": "0.875rem",
        "4": "1rem",
        "5": "1.25rem",
        "6": "1.5rem",
        "7": "1.75rem",
        "8": "2rem",
        "9": "2.25rem",
        "10": "2.5rem",
        "12": "3rem",
        "16": "4rem",
        "20": "5rem",
        "24": "6rem",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      lineHeight: {
        none: "1",
        tight: "1.25",
        snug: "1.375",
        normal: "1.5",
        relaxed: "1.625",
        loose: "2",
        "3": "0.75rem",
        "4": "1rem",
        "5": "1.25rem",
        "6": "1.5rem",
        "7": "1.75rem",
        "8": "2rem",
        "10": "2.5rem",
      },
      fontWeight: {
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
      },
      // The desktop's named type scale, read out of its compiled stylesheet. Its
      // markup writes `text-body-base` / `text-caption-base` rather than raw sizes,
      // so the reading column cannot be reproduced without these names.
      fontSize: {
        "body-base": ["14px", { lineHeight: "22px", letterSpacing: "-0.1px" }],
        "caption-base": ["12px", { lineHeight: "18px", letterSpacing: "0" }],
        "activity-body-small": [
          "14px",
          { lineHeight: "22px", letterSpacing: "0" },
        ],
        "caption-small-strong": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0" },
        ],
      },
    },
  },
  plugins: [],
  // The shell uses a small set of token-derived utilities; the safelist
  // guarantees that the brief's named examples are present in the compiled
  // stylesheet even when a state-specific branch is not visible to Tailwind's
  // static class scan.
  safelist: [
    "bg-bg_default_primary",
    "bg-bg_default_secondary",
    "bg-bg_grouped_primary",
    "bg-bg_grouped_secondary",
    "bg-bg_interaction_primary_default",
    "bg-bg_interaction_primary_hover",
    "bg-bg_interaction_primary_selected",
    "text-text_default_primary",
    "text-text_default_secondary",
    "text-text_default_tertiary",
    "text-text_label_secondary_default",
    "border-border_default",
    "border-border_heavy",
    "rounded-radius_4",
    "rounded-radius_8",
    "rounded-radius_12",
    "rounded-radius_16",
    "rounded-radius_20",
    "rounded-radius_24",
    "rounded-radius_32",
    "rounded-radius_full",
    "size-size_12",
    "size-size_14",
    "size-size_16",
    "size-size_20",
    "size-size_24",
    "leading-line_height_16",
    "leading-line_height_20",
    "leading-line_height_22",
    "leading-line_height_26",
    "leading-line_height_28",
    "gap-spacing_4",
    "gap-spacing_6",
    "gap-spacing_8",
    "gap-spacing_12",
    "gap-spacing_16",
    "shadow-shadow_default",
    // The mono stack the desktop's preflight gives `code`/`kbd`/`pre`/`samp` is also a
    // utility the conversation surface needs for inline code; keep it generated even
    // while no shell element currently carries it.
    "font-mono",
  ],
};

module.exports = tailwindConfig;
