// Tailwind v3 config for the WebUI shell (ADR 0009, ADR 0010).
//
// Token names map 1:1 onto the desktop application's design tokens
// (see docs/webui-visual-language.md and packages/webui/src/client/styles/tokens.css).
// Every utility whose name starts with a token family — bg_*, text_*, border_*,
// shadow_*, radius_*, spacing_*, size_*, line_height_* — is generated from the
// corresponding CSS variable so the WebUI and the desktop application share
// one naming surface.

const tailwindConfig = {
  content: [
    "./src/client/**/*.{ts,tsx,html}",
  ],
  theme: {
    backgroundColor: {
      transparent: "transparent",
      current: "currentColor",
      inherit: "inherit",
      "bg_default_primary": "var(--bg-default-primary)",
      "bg_default_primary_elevated": "var(--bg-default-primary-elevated)",
      "bg_default_scrim": "var(--bg-default-scrim)",
      "bg_default_secondary": "var(--bg-default-secondary)",
      "bg_default_secondary_elevated": "var(--bg-default-secondary-elevated)",
      "bg_default_tertiary": "var(--bg-default-tertiary)",
      "bg_default_tertiary_elevated": "var(--bg-default-tertiary-elevated)",
      "bg_grouped_primary": "var(--bg-grouped-primary)",
      "bg_grouped_primary_elevated": "var(--bg-grouped-primary-elevated)",
      "bg_grouped_secondary": "var(--bg-grouped-secondary)",
      "bg_grouped_secondary_elevated": "var(--bg-grouped-secondary-elevated)",
      "bg_grouped_tertiary": "var(--bg-grouped-tertiary)",
      "bg_grouped_tertiary_elevated": "var(--bg-grouped-tertiary-elevated)",
      "bg_interaction_accent_default": "var(--bg-interaction-accent-default)",
      "bg_interaction_accent_focus_blue": "var(--bg-interaction-accent-focus-blue)",
      "bg_interaction_accent_focus_highlight": "var(--bg-interaction-accent-focus-highlight)",
      "bg_interaction_accent_hover": "var(--bg-interaction-accent-hover)",
      "bg_interaction_accent_inactive": "var(--bg-interaction-accent-inactive)",
      "bg_interaction_accent_press": "var(--bg-interaction-accent-press)",
      "bg_interaction_danger_primary_default": "var(--bg-interaction-danger-primary-default)",
      "bg_interaction_danger_primary_hover": "var(--bg-interaction-danger-primary-hover)",
      "bg_interaction_danger_primary_inactive": "var(--bg-interaction-danger-primary-inactive)",
      "bg_interaction_danger_primary_press": "var(--bg-interaction-danger-primary-press)",
      "bg_interaction_danger_secondary_default": "var(--bg-interaction-danger-secondary-default)",
      "bg_interaction_danger_secondary_hover": "var(--bg-interaction-danger-secondary-hover)",
      "bg_interaction_danger_secondary_inactive": "var(--bg-interaction-danger-secondary-inactive)",
      "bg_interaction_danger_secondary_press": "var(--bg-interaction-danger-secondary-press)",
      "bg_interaction_positive_default": "var(--bg-interaction-positive-default)",
      "bg_interaction_positive_hover": "var(--bg-interaction-positive-hover)",
      "bg_interaction_positive_inactive": "var(--bg-interaction-positive-inactive)",
      "bg_interaction_positive_press": "var(--bg-interaction-positive-press)",
      "bg_interaction_primary_default": "var(--bg-interaction-primary-default)",
      "bg_interaction_primary_hover": "var(--bg-interaction-primary-hover)",
      "bg_interaction_primary_inactive": "var(--bg-interaction-primary-inactive)",
      "bg_interaction_primary_press": "var(--bg-interaction-primary-press)",
      "bg_interaction_primary_selected": "var(--bg-interaction-primary-selected)",
      "bg_interaction_secondary_default": "var(--bg-interaction-secondary-default)",
      "bg_interaction_secondary_hover": "var(--bg-interaction-secondary-hover)",
      "bg_interaction_secondary_inactive": "var(--bg-interaction-secondary-inactive)",
      "bg_interaction_secondary_press": "var(--bg-interaction-secondary-press)",
      "bg_interaction_secondary_selected": "var(--bg-interaction-secondary-selected)",
      "bg_interaction_tertiary_default": "var(--bg-interaction-tertiary-default)",
      "bg_interaction_tertiary_hover": "var(--bg-interaction-tertiary-hover)",
      "bg_interaction_tertiary_inactive": "var(--bg-interaction-tertiary-inactive)",
      "bg_interaction_tertiary_press": "var(--bg-interaction-tertiary-press)",
      "bg_interaction_tertiary_selected": "var(--bg-interaction-tertiary-selected)",
      "bg_interaction_video_generation_default": "var(--bg-interaction-video-generation-default)",
      "bg_interaction_video_generation_hover": "var(--bg-interaction-video-generation-hover)",
      "bg_interaction_video_generation_selected": "var(--bg-interaction-video-generation-selected)",
      "bg_interaction_warning_default": "var(--bg-interaction-warning-default)",
      "bg_interaction_warning_hover": "var(--bg-interaction-warning-hover)",
      "bg_interaction_warning_inactive": "var(--bg-interaction-warning-inactive)",
      "bg_interaction_warning_press": "var(--bg-interaction-warning-press)",
      "bg_status_blue": "var(--bg-status-blue)",
      "bg_status_error": "var(--bg-status-error)",
      "bg_status_positive": "var(--bg-status-positive)",
      "bg_status_tag": "var(--bg-status-tag)",
      "bg_status_video_generation": "var(--bg-status-video-generation)",
      "bg_status_warning": "var(--bg-status-warning)",
      "utility_overlay": "var(--utility-overlay)",
      "utility_popover": "var(--utility-popover)",
      "utility_scrim": "var(--utility-scrim)",
      "utility_scrollbar": "var(--utility-scrollbar)",
      "utility_tootip": "var(--utility-tootip)",
    },
    textColor: {
      transparent: "transparent",
      current: "currentColor",
      inherit: "inherit",
      "text_default_accent": "var(--text-default-accent)",
      "text_default_inverted": "var(--text-default-inverted)",
      "text_default_inverted_static": "var(--text-default-inverted-static)",
      "text_default_primary": "var(--text-default-primary)",
      "text_default_quaternary": "var(--text-default-quaternary)",
      "text_default_secondary": "var(--text-default-secondary)",
      "text_default_tertiary": "var(--text-default-tertiary)",
      "text_label_accent_default": "var(--text-label-accent-default)",
      "text_label_accent_hover": "var(--text-label-accent-hover)",
      "text_label_accent_inactive": "var(--text-label-accent-inactive)",
      "text_label_accent_press": "var(--text-label-accent-press)",
      "text_label_danger_primary_default": "var(--text-label-danger-primary-default)",
      "text_label_danger_primary_hover": "var(--text-label-danger-primary-hover)",
      "text_label_danger_primary_inactive": "var(--text-label-danger-primary-inactive)",
      "text_label_danger_primary_press": "var(--text-label-danger-primary-press)",
      "text_label_danger_secondary_default": "var(--text-label-danger-secondary-default)",
      "text_label_danger_secondary_hover": "var(--text-label-danger-secondary-hover)",
      "text_label_danger_secondary_inactive": "var(--text-label-danger-secondary-inactive)",
      "text_label_danger_secondary_press": "var(--text-label-danger-secondary-press)",
      "text_label_positive_primary_default": "var(--text-label-positive-primary-default)",
      "text_label_positive_primary_hover": "var(--text-label-positive-primary-hover)",
      "text_label_positive_primary_inactive": "var(--text-label-positive-primary-inactive)",
      "text_label_positive_primary_press": "var(--text-label-positive-primary-press)",
      "text_label_positive_secondary_default": "var(--text-label-positive-secondary-default)",
      "text_label_positive_secondary_hover": "var(--text-label-positive-secondary-hover)",
      "text_label_positive_secondary_inactive": "var(--text-label-positive-secondary-inactive)",
      "text_label_positive_secondary_press": "var(--text-label-positive-secondary-press)",
      "text_label_primary_default": "var(--text-label-primary-default)",
      "text_label_primary_hover": "var(--text-label-primary-hover)",
      "text_label_primary_inactive": "var(--text-label-primary-inactive)",
      "text_label_primary_press": "var(--text-label-primary-press)",
      "text_label_primary_selected": "var(--text-label-primary-selected)",
      "text_label_secondary_default": "var(--text-label-secondary-default)",
      "text_label_secondary_hover": "var(--text-label-secondary-hover)",
      "text_label_secondary_inactive": "var(--text-label-secondary-inactive)",
      "text_label_secondary_press": "var(--text-label-secondary-press)",
      "text_label_secondary_selected": "var(--text-label-secondary-selected)",
      "text_label_tertiary_default": "var(--text-label-tertiary-default)",
      "text_label_tertiary_hover": "var(--text-label-tertiary-hover)",
      "text_label_tertiary_inactive": "var(--text-label-tertiary-inactive)",
      "text_label_tertiary_press": "var(--text-label-tertiary-press)",
      "text_label_tertiary_selected": "var(--text-label-tertiary-selected)",
      "text_label_warning_primary_default": "var(--text-label-warning-primary-default)",
      "text_label_warning_primary_hover": "var(--text-label-warning-primary-hover)",
      "text_label_warning_primary_inactive": "var(--text-label-warning-primary-inactive)",
      "text_label_warning_primary_press": "var(--text-label-warning-primary-press)",
      "text_label_warning_secondary_default": "var(--text-label-warning-secondary-default)",
      "text_label_warning_secondary_hover": "var(--text-label-warning-secondary-hover)",
      "text_label_warning_secondary_inactive": "var(--text-label-warning-secondary-inactive)",
      "text_label_warning_secondary_press": "var(--text-label-warning-secondary-press)",
      "text_status_banana": "var(--text-status-banana)",
      "text_status_blue": "var(--text-status-blue)",
      "text_status_error": "var(--text-status-error)",
      "text_status_success": "var(--text-status-success)",
      "text_status_video_generation": "var(--text-status-video-generation)",
      "text_status_warning": "var(--text-status-warning)",
      "icon_default_accent": "var(--icon-default-accent)",
      "icon_default_inverted": "var(--icon-default-inverted)",
      "icon_default_inverted_static": "var(--icon-default-inverted-static)",
      "icon_default_primary": "var(--icon-default-primary)",
      "icon_default_quaternary": "var(--icon-default-quaternary)",
      "icon_default_secondary": "var(--icon-default-secondary)",
      "icon_default_tertiary": "var(--icon-default-tertiary)",
      "icon_interaction_accent_accent": "var(--icon-interaction-accent-accent)",
      "icon_interaction_accent_default": "var(--icon-interaction-accent-default)",
      "icon_interaction_accent_hover": "var(--icon-interaction-accent-hover)",
      "icon_interaction_accent_inactive": "var(--icon-interaction-accent-inactive)",
      "icon_interaction_accent_press": "var(--icon-interaction-accent-press)",
      "icon_interaction_danger_primary_default": "var(--icon-interaction-danger-primary-default)",
      "icon_interaction_danger_primary_hover": "var(--icon-interaction-danger-primary-hover)",
      "icon_interaction_danger_primary_inactive": "var(--icon-interaction-danger-primary-inactive)",
      "icon_interaction_danger_primary_press": "var(--icon-interaction-danger-primary-press)",
      "icon_interaction_danger_secondary_default": "var(--icon-interaction-danger-secondary-default)",
      "icon_interaction_danger_secondary_hover": "var(--icon-interaction-danger-secondary-hover)",
      "icon_interaction_danger_secondary_inactive": "var(--icon-interaction-danger-secondary-inactive)",
      "icon_interaction_danger_secondary_press": "var(--icon-interaction-danger-secondary-press)",
      "icon_interaction_positive_primary_default": "var(--icon-interaction-positive-primary-default)",
      "icon_interaction_positive_primary_hover": "var(--icon-interaction-positive-primary-hover)",
      "icon_interaction_positive_primary_inactive": "var(--icon-interaction-positive-primary-inactive)",
      "icon_interaction_positive_primary_press": "var(--icon-interaction-positive-primary-press)",
      "icon_interaction_positive_secondary_default": "var(--icon-interaction-positive-secondary-default)",
      "icon_interaction_positive_secondary_hover": "var(--icon-interaction-positive-secondary-hover)",
      "icon_interaction_positive_secondary_inactive": "var(--icon-interaction-positive-secondary-inactive)",
      "icon_interaction_positive_secondary_press": "var(--icon-interaction-positive-secondary-press)",
      "icon_interaction_primary_default": "var(--icon-interaction-primary-default)",
      "icon_interaction_primary_hover": "var(--icon-interaction-primary-hover)",
      "icon_interaction_primary_inactive": "var(--icon-interaction-primary-inactive)",
      "icon_interaction_primary_press": "var(--icon-interaction-primary-press)",
      "icon_interaction_primary_selected": "var(--icon-interaction-primary-selected)",
      "icon_interaction_secondary_default": "var(--icon-interaction-secondary-default)",
      "icon_interaction_secondary_hover": "var(--icon-interaction-secondary-hover)",
      "icon_interaction_secondary_inactive": "var(--icon-interaction-secondary-inactive)",
      "icon_interaction_secondary_press": "var(--icon-interaction-secondary-press)",
      "icon_interaction_secondary_selected": "var(--icon-interaction-secondary-selected)",
      "icon_interaction_tertiary_default": "var(--icon-interaction-tertiary-default)",
      "icon_interaction_tertiary_hover": "var(--icon-interaction-tertiary-hover)",
      "icon_interaction_tertiary_inactive": "var(--icon-interaction-tertiary-inactive)",
      "icon_interaction_tertiary_press": "var(--icon-interaction-tertiary-press)",
      "icon_interaction_tertiary_selected": "var(--icon-interaction-tertiary-selected)",
      "icon_interaction_warning_primary_default": "var(--icon-interaction-warning-primary-default)",
      "icon_interaction_warning_primary_hover": "var(--icon-interaction-warning-primary-hover)",
      "icon_interaction_warning_primary_inactive": "var(--icon-interaction-warning-primary-inactive)",
      "icon_interaction_warning_primary_press": "var(--icon-interaction-warning-primary-press)",
      "icon_interaction_warning_secondary_default": "var(--icon-interaction-warning-secondary-default)",
      "icon_interaction_warning_secondary_hover": "var(--icon-interaction-warning-secondary-hover)",
      "icon_interaction_warning_secondary_inactive": "var(--icon-interaction-warning-secondary-inactive)",
      "icon_interaction_warning_secondary_press": "var(--icon-interaction-warning-secondary-press)",
      "icon_status_error": "var(--icon-status-error)",
      "icon_status_success": "var(--icon-status-success)",
      "icon_status_warning": "var(--icon-status-warning)",
      "terminal_ansi_black": "var(--terminal-ansi-black)",
      "terminal_ansi_blue": "var(--terminal-ansi-blue)",
      "terminal_ansi_bright_black": "var(--terminal-ansi-bright-black)",
      "terminal_ansi_bright_blue": "var(--terminal-ansi-bright-blue)",
      "terminal_ansi_bright_cyan": "var(--terminal-ansi-bright-cyan)",
      "terminal_ansi_bright_green": "var(--terminal-ansi-bright-green)",
      "terminal_ansi_bright_magenta": "var(--terminal-ansi-bright-magenta)",
      "terminal_ansi_bright_red": "var(--terminal-ansi-bright-red)",
      "terminal_ansi_bright_white": "var(--terminal-ansi-bright-white)",
      "terminal_ansi_bright_yellow": "var(--terminal-ansi-bright-yellow)",
      "terminal_ansi_cyan": "var(--terminal-ansi-cyan)",
      "terminal_ansi_green": "var(--terminal-ansi-green)",
      "terminal_ansi_magenta": "var(--terminal-ansi-magenta)",
      "terminal_ansi_red": "var(--terminal-ansi-red)",
      "terminal_ansi_white": "var(--terminal-ansi-white)",
      "terminal_ansi_yellow": "var(--terminal-ansi-yellow)",
      "terminal_cursor": "var(--terminal-cursor)",
      "terminal_cursor_accent": "var(--terminal-cursor-accent)",
      "terminal_foreground": "var(--terminal-foreground)",
      "terminal_selection": "var(--terminal-selection)",
    },
    borderColor: {
      transparent: "transparent",
      current: "currentColor",
      inherit: "inherit",
      "border_accent": "var(--border-accent)",
      "border_danger_default": "var(--border-danger-default)",
      "border_danger_hover": "var(--border-danger-hover)",
      "border_danger_inactive": "var(--border-danger-inactive)",
      "border_danger_press": "var(--border-danger-press)",
      "border_default": "var(--border-default)",
      "border_heavy": "var(--border-heavy)",
      "border_light": "var(--border-light)",
      "border_status_blue": "var(--border-status-blue)",
      "border_status_error": "var(--border-status-error)",
      "border_status_success": "var(--border-status-success)",
      "border_status_warning": "var(--border-status-warning)",
      "border_tertiary_default": "var(--border-tertiary-default)",
      "border_tertiary_hover": "var(--border-tertiary-hover)",
      "border_tertiary_inactive": "var(--border-tertiary-inactive)",
      "border_tertiary_press": "var(--border-tertiary-press)",
    },
    boxShadow: {
      none: "none",
      "shadow_default": "var(--shadow-default)",
    },
    borderRadius: {
      none: "0",
      full: "9999px",
      "radius_12": "var(--radius-12)",
      "radius_16": "var(--radius-16)",
      "radius_20": "var(--radius-20)",
      "radius_24": "var(--radius-24)",
      "radius_32": "var(--radius-32)",
      "radius_4": "var(--radius-4)",
      "radius_8": "var(--radius-8)",
      "radius_full": "var(--radius-full)",
    },
    spacing: {
      "spacing_0": "var(--spacing-0)",
      "spacing_12": "var(--spacing-12)",
      "spacing_128": "var(--spacing-128)",
      "spacing_16": "var(--spacing-16)",
      "spacing_2": "var(--spacing-2)",
      "spacing_20": "var(--spacing-20)",
      "spacing_24": "var(--spacing-24)",
      "spacing_32": "var(--spacing-32)",
      "spacing_4": "var(--spacing-4)",
      "spacing_40": "var(--spacing-40)",
      "spacing_48": "var(--spacing-48)",
      "spacing_6": "var(--spacing-6)",
      "spacing_64": "var(--spacing-64)",
      "spacing_8": "var(--spacing-8)",
      "spacing_90": "var(--spacing-90)",
      "size_12": "var(--size-12)",
      "size_14": "var(--size-14)",
      "size_16": "var(--size-16)",
      "size_20": "var(--size-20)",
      "size_24": "var(--size-24)",
      "size_32": "var(--size-32)",
      "size_40": "var(--size-40)",
      "size_48": "var(--size-48)",
      "size_64": "var(--size-64)",
    },
    size: {
      "size_12": "var(--size-12)",
      "size_14": "var(--size-14)",
      "size_16": "var(--size-16)",
      "size_20": "var(--size-20)",
      "size_24": "var(--size-24)",
      "size_32": "var(--size-32)",
      "size_40": "var(--size-40)",
      "size_48": "var(--size-48)",
      "size_64": "var(--size-64)",
    },
    lineHeight: {
      "line_height_16": "var(--line-height-16)",
      "line_height_18": "var(--line-height-18)",
      "line_height_20": "var(--line-height-20)",
      "line_height_22": "var(--line-height-22)",
      "line_height_26": "var(--line-height-26)",
      "line_height_28": "var(--line-height-28)",
      "line_height_36": "var(--line-height-36)",
      "line_height_40": "var(--line-height-40)",
    },
    fontWeight: {
      "weight_medium": "var(--weight-medium)",
      "weight_regular": "var(--weight-regular)",
    },
    fontFamily: {
      sans: [
        '"HarmonyOS Sans"',
        '"Segoe UI"',
        '"SF Pro Display"',
        "-apple-system",
        "BlinkMacSystemFont",
        "Roboto",
        "Oxygen",
        "Ubuntu",
        "Cantarell",
        '"Open Sans"',
        '"Helvetica Neue"',
        "sans-serif",
        // Chinese fallbacks — desktop's preflight stack.
        '"HarmonyOS Sans SC"',
        '"PingFang SC"',
        '"Hiragino Sans GB"',
        '"Microsoft Yahei UI"',
        '"Microsoft Yahei"',
        '"Source Han Sans CN"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Apple Color Emoji"',
        '"Twemoji Mozilla"',
        '"Noto Color Emoji"',
        '"Android Emoji"',
      ],
      serif: ['"SourceSerif"', '"Source Serif Pro"', "Georgia", "serif"],
      mono: [
        '"Hack"',
        "ui-monospace",
        "SFMono-Regular",
        '"SF Mono"',
        "Menlo",
        "Consolas",
        // Chinese fallbacks — desktop's preflight stack.
        '"HarmonyOS Sans SC"',
        '"PingFang SC"',
        "monospace",
      ],
    },
    extend: {
      colors: {
      "blue_400": "var(--blue-400)",
      "blue_500": "var(--blue-500)",
      "blue_600": "var(--blue-600)",
      "violet_500": "var(--violet-500)",
      },
    },
  },
  plugins: [],
  // The shell uses a small set of token-derived utilities; the safelist
  // guarantees that the brief's named examples are present in the
  // compiled stylesheet even if no source file currently references them
  // (later tickets will adopt them as the conversation surface grows).
  safelist: [
    "bg-bg_default_primary",
    "bg-bg_default_secondary",
    "bg-bg_grouped_primary",
    "bg-bg_grouped_secondary",
    "bg-bg_interaction_primary_default",
    "bg-bg_interaction_primary_hover",
    "bg-bg_interaction_primary_selected",
    "text-text_default_primary",
    "text-text_default_secondary",
    "text-text_default_tertiary",
    "text-text_label_secondary_default",
    "border-border_default",
    "border-border_heavy",
    "rounded-radius_4",
    "rounded-radius_8",
    "rounded-radius_12",
    "rounded-radius_16",
    "rounded-radius_20",
    "rounded-radius_24",
    "rounded-radius_32",
    "rounded-radius_full",
    "size-size_12",
    "size-size_14",
    "size-size_16",
    "size-size_20",
    "size-size_24",
    "leading-line_height_16",
    "leading-line_height_20",
    "leading-line_height_22",
    "leading-line_height_26",
    "leading-line_height_28",
    "gap-spacing_4",
    "gap-spacing_6",
    "gap-spacing_8",
    "gap-spacing_12",
    "gap-spacing_16",
    "shadow-shadow_default",
  ],
};

module.exports = tailwindConfig;
